spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/GuhTiagoSilva/user-order-management-config
server:
  port: 8888
